const lessons = [
    [ // Bài 1
        { vietnamese: "Nam giới", kanji: "男性", hiragana: "だんせい", example: "男性用の服を買いました。" },
        { vietnamese: "Nữ giới", kanji: "女性", hiragana: "じょせい", example: "女性が多い職場です。" },
        { vietnamese: "Cao tuổi", kanji: "高齢", hiragana: "こうれい", example: "高齢の方に席を譲りました。" },
        { vietnamese: "Hơn tuổi", kanji: "年上", hiragana: "としうえ", example: "年上の人に敬意を払います。" },
        { vietnamese: "Cấp trên", kanji: "目上", hiragana: "めうえ", example: "目上の人に丁寧に話します。" },
        { vietnamese: "Tiền bối", kanji: "先輩", hiragana: "せんぱい", example: "先輩に仕事を教わりました。" },
        { vietnamese: "Hậu bối", kanji: "後輩", hiragana: "こうはい", example: "後輩を指導しています。" },
        { vietnamese: "Cấp trên", kanji: "上司", hiragana: "じょうし", example: "上司から指示を受けました。" },
        { vietnamese: "Đối phương", kanji: "相手", hiragana: "あいて", example: "相手の気持ちを考えます。" },
        { vietnamese: "Người quen", kanji: "知り合い", hiragana: "しりあい", example: "知り合いがパーティーに来ました。" },
        { vietnamese: "Bạn hữu", kanji: "友人", hiragana: "ゆうじん", example: "友人と旅行に行きます。" },
        { vietnamese: "Quan hệ", kanji: "仲", hiragana: "なか", example: "仲の良い友達がいます。" },
        { vietnamese: "Ngày tháng năm sinh", kanji: "生年月日", hiragana: "せいねんがっぴ", example: "生年月日を記入してください。" },
        { vietnamese: "Ra đời", kanji: "誕生", hiragana: "たんじょう", example: "誕生を祝いました。" },
        { vietnamese: "Năm, tuổi", kanji: "年", hiragana: "とし", example: "年を取るのが怖いです。" },
        { vietnamese: "Xuất thân", kanji: "出身", hiragana: "しゅっしん", example: "出身はどこですか？" },
        { vietnamese: "Quê hương", kanji: "故郷", hiragana: "ふるさと", example: "故郷に帰りたいです。" },
        { vietnamese: "Trưởng thành", kanji: "成長", hiragana: "せいちょう", example: "子供が成長しました。" },
        { vietnamese: "Người lớn", kanji: "成人", hiragana: "せいじん", example: "成人式に参加しました。" },
        { vietnamese: "Đỗ", kanji: "合格", hiragana: "ごうかく", example: "試験に合格しました。" },
        { vietnamese: "Học lên", kanji: "進学", hiragana: "しんがく", example: "大学に進学します。" },
        { vietnamese: "Bỏ học", kanji: "退学", hiragana: "たいがく", example: "退学を決めました。" },
        { vietnamese: "Tìm việc", kanji: "就職", hiragana: "しゅうしょく", example: "就職活動を始めました。" },
        { vietnamese: "Nghỉ việc", kanji: "退職", hiragana: "たいしょく", example: "会社を退職しました。" },
        { vietnamese: "Thất nghiệp", kanji: "失業", hiragana: "しつぎょう", example: "失業して困っています。" },
        { vietnamese: "Tăng ca", kanji: "残業", hiragana: "ざんぎょう", example: "残業が多いです。" },
        { vietnamese: "Sinh hoạt", kanji: "生活", hiragana: "せいかつ", example: "生活が忙しいです。" },
        { vietnamese: "Đi làm", kanji: "通勤", hiragana: "つうきん", example: "通勤に時間がかかります。" },
        { vietnamese: "Quá trình học", kanji: "学歴", hiragana: "がくれき", example: "学歴を重視する会社です。" },
        { vietnamese: "Lương", kanji: "給料", hiragana: "きゅうりょう", example: "給料が上がりました。" }
    ],
    [ // Bài 2
        { vietnamese: "Phỏng vấn", kanji: "面接", hiragana: "めんせつ", example: "明日は面接があります。" },
  { vietnamese: "Giải lao", kanji: "休憩", hiragana: "きゅうけい", example: "15分間休憩しましょう。" },
  { vietnamese: "Tham quan", kanji: "観光", hiragana: "かんこう", example: "京都で観光を楽しんだ。" },
  { vietnamese: "Về nước", kanji: "帰国", hiragana: "きこく", example: "来月帰国します。" },
  { vietnamese: "Về quê", kanji: "帰省", hiragana: "きせい", example: "夏休みに帰省する予定だ。" },
  { vietnamese: "Về nhà", kanji: "帰宅", hiragana: "きたく", example: "夜遅く帰宅した。" },
  { vietnamese: "Tham gia", kanji: "参加", hiragana: "さんか", example: "会議に参加してください。" },
  { vietnamese: "Tham dự", kanji: "出席", hiragana: "しゅっせき", example: "授業に出席する。" },
  { vietnamese: "Vắng mặt", kanji: "欠席", hiragana: "けっせき", example: "病気で欠席します。" },
  { vietnamese: "Đi muộn", kanji: "遅刻", hiragana: "ちこく", example: "電車が遅れて遅刻した。" },
  { vietnamese: "Trang điểm", kanji: "化粧", hiragana: "けしょう", example: "毎朝化粧をする。" },
  { vietnamese: "Tính toán", kanji: "計算", hiragana: "けいさん", example: "費用を計算する。" },
  { vietnamese: "Kế hoạch", kanji: "計画", hiragana: "けいかく", example: "旅行の計画を立てる。" },
  { vietnamese: "Thành công", kanji: "成功", hiragana: "せいこう", example: "プロジェクトが成功した。" },
  { vietnamese: "Thất bại", kanji: "失敗", hiragana: "しっぱい", example: "失敗から学ぶことが多い。" },
  { vietnamese: "Chuẩn bị", kanji: "準備", hiragana: "じゅんび", example: "試験の準備をする。" },
  { vietnamese: "Sắp xếp", kanji: "整理", hiragana: "せいり", example: "部屋を整理する。" },
  { vietnamese: "Gọi món", kanji: "注文", hiragana: "ちゅうもん", example: "料理を注文する。" },
  { vietnamese: "Tiết kiệm", kanji: "貯金", hiragana: "ちょきん", example: "毎月貯金をする。" },
  { vietnamese: "Suốt đêm", kanji: "徹夜", hiragana: "てつや", example: "試験前に徹夜した。" },
  { vietnamese: "Chuyển nhà", kanji: "引越し", hiragana: "ひっこし", example: "来月引越しする。" },
  { vietnamese: "Chiều cao", kanji: "身長", hiragana: "しんちょう", example: "身長を測る。" },
  { vietnamese: "Cân nặng", kanji: "体重", hiragana: "たいじゅう", example: "体重が増えた。" },
  { vietnamese: "Vết thương", kanji: "怪我", hiragana: "けが", example: "足に怪我をした。" },
  { vietnamese: "Hội", kanji: "会", hiragana: "かい", example: "同窓会に出席する。" },
  { vietnamese: "Sở thích", kanji: "趣味", hiragana: "しゅみ", example: "趣味は写真です。" },
  { vietnamese: "Yêu thích", kanji: "興味", hiragana: "きょうみ", example: "日本文化に興味がある。" },
  { vietnamese: "Kỷ niệm", kanji: "思い出", hiragana: "おもいで", example: "いい思い出を作る。" },
  { vietnamese: "Đùa", kanji: "冗談", hiragana: "じょうだん", example: "冗談を言う。" },
  { vietnamese: "Mục đích", kanji: "目的", hiragana: "もくてき", example: "目的を達成する。" }
    ],
    [ // Bài 3
        { vietnamese: "Hứa hẹn", kanji: "約束", hiragana: "やくそく", example: "友達と約束をした。" },
  { vietnamese: "Nói chuyện", kanji: "お喋り", hiragana: "おしゃべり", example: "授業中にお喋りしないでください。" },
  { vietnamese: "Ngại ngùng", kanji: "遠慮", hiragana: "えんりょ", example: "遠慮なく食べてください。" },
  { vietnamese: "Chịu đựng", kanji: "我慢", hiragana: "がまん", example: "痛みを我慢する。" },
  { vietnamese: "Làm phiền", kanji: "迷惑", hiragana: "めいわく", example: "夜遅く電話するのは迷惑だ。" },
  { vietnamese: "Nguyện vọng", kanji: "希望", hiragana: "きぼう", example: "大学に入ることを希望している。" },
  { vietnamese: "Mơ", kanji: "夢", hiragana: "ゆめ", example: "将来の夢は医者になることだ。" },
  { vietnamese: "Tán thành", kanji: "賛成", hiragana: "さんせい", example: "その計画に賛成です。" },
  { vietnamese: "Phản đối", kanji: "反対", hiragana: "はんだい", example: "その意見に反対する。" },
  { vietnamese: "Tưởng tượng", kanji: "想像", hiragana: "そうぞう", example: "未来を想像する。" },
  { vietnamese: "Nỗ lực", kanji: "努力", hiragana: "どりょく", example: "成功するために努力する。" },
  { vietnamese: "Mặt trời", kanji: "太陽", hiragana: "たいよう", example: "太陽が昇る。" },
  { vietnamese: "Trái đất", kanji: "地球", hiragana: "ちきゅう", example: "地球は青く美しい。" },
  { vietnamese: "Nhiệt độ", kanji: "温度", hiragana: "おんど", example: "温度が上がる。" },
  { vietnamese: "Độ ẩm", kanji: "湿度", hiragana: "しつど", example: "湿度が高い日は暑く感じる。" },
  { vietnamese: "Hơi ẩm", kanji: "湿気", hiragana: "しっけ", example: "部屋の湿気を取る。" },
  { vietnamese: "Mùa mưa", kanji: "梅雨", hiragana: "つゆ", example: "梅雨の時期は洗濯物が乾きにくい。" },
  { vietnamese: "Nấm mốc", kanji: "黴", hiragana: "かび", example: "パンに黴が生えた。" },
  { vietnamese: "Điều hòa ấm", kanji: "暖房", hiragana: "だんぼう", example: "冬は暖房をつける。" },
  { vietnamese: "Vỏ", kanji: "皮", hiragana: "かわ", example: "りんごの皮をむく。" },
  { vietnamese: "Lon", kanji: "缶", hiragana: "かん", example: "缶ジュースを買う。" },
  { vietnamese: "Màn hình", kanji: "画面", hiragana: "がめん", example: "画面が暗くなった。" },
  { vietnamese: "Chương trình", kanji: "番組", hiragana: "ばんぐみ", example: "テレビ番組を見る。" },
  { vietnamese: "Kí sự", kanji: "記事", hiragana: "きじ", example: "新聞の記事を読む。" },
  { vietnamese: "Hàng xóm", kanji: "近所", hiragana: "きんじょ", example: "近所の人と挨拶する。" },
  { vietnamese: "Cảnh sát", kanji: "警察", hiragana: "けいさつ", example: "警察に届け出る。" },
  { vietnamese: "Thủ phạm", kanji: "犯人", hiragana: "はんにん", example: "犯人が捕まった。" },
  { vietnamese: "Tiền lẻ", kanji: "小銭", hiragana: "こぜに", example: "小銭がない。" },
  { vietnamese: "Bữa ăn ngon", kanji: "ご馳走", hiragana: "ごちそう", example: "ご馳走様でした。" },
  { vietnamese: "Tác giả", kanji: "作者", hiragana: "さくしゃ", example: "この本の作者は有名だ。" }
    ],
    [ // Bài 4
        { vietnamese: "Tác phẩm", kanji: "作品", hiragana: "さくひん", example: "この作品はとても人気がある。" },
  { vietnamese: "Đồng phục", kanji: "制服", hiragana: "せいふく", example: "学生は制服を着なければならない。" },
  { vietnamese: "Chất tẩy rửa", kanji: "洗剤", hiragana: "せんざい", example: "洗剤で服を洗う。" },
  { vietnamese: "Đáy", kanji: "底", hiragana: "そこ", example: "瓶の底にコインがある。" },
  { vietnamese: "Tầng hầm", kanji: "地下", hiragana: "ちか", example: "地下に駐車場がある。" },
  { vietnamese: "Chùa", kanji: "寺", hiragana: "てら", example: "京都には古い寺が多い。" },
  { vietnamese: "Con đường", kanji: "道路", hiragana: "どうろ", example: "道路を渡る時は気をつけてください。" },
  { vietnamese: "Con dốc", kanji: "坂", hiragana: "さか", example: "この坂はとても急だ。" },
  { vietnamese: "Khói", kanji: "煙", hiragana: "けむり", example: "煙が空に上がっている。" },
  { vietnamese: "Tro", kanji: "灰", hiragana: "はい", example: "灰を灰皿に捨てる。" },
  { vietnamese: "Kích cỡ", kanji: "判", hiragana: "はん", example: "この判の紙をください。" },
  { vietnamese: "Danh thiếp", kanji: "名刺", hiragana: "めいし", example: "名刺を交換する。" },
  { vietnamese: "Giấy phép", kanji: "免許", hiragana: "めんきょ", example: "運転免許を取った。" },
  { vietnamese: "Nhiều", kanji: "多く", hiragana: "おおく", example: "多くの人が集まった。" },
  { vietnamese: "Phần đầu", kanji: "前半", hiragana: "ぜんはん", example: "試合の前半は負けていた。" },
  { vietnamese: "Phần cuối", kanji: "後半", hiragana: "こうはん", example: "後半で逆転した。" },
  { vietnamese: "Tuyệt vời", kanji: "最高", hiragana: "さいこう", example: "今日の天気は最高だ。" },
  { vietnamese: "Tệ hại", kanji: "最低", hiragana: "さいてい", example: "彼の態度は最低だ。" },
  { vietnamese: "Đầu tiên", kanji: "最初", hiragana: "さいしょ", example: "最初からやり直す。" },
  { vietnamese: "Cuối cùng", kanji: "最後", hiragana: "さいご", example: "最後まで諦めない。" },
  { vietnamese: "Tự động", kanji: "自動", hiragana: "じどう", example: "自動ドアが開いた。" },
  { vietnamese: "Chủng loại", kanji: "種類", hiragana: "しゅるい", example: "この店は種類が豊富だ。" },
  { vietnamese: "Tính cách", kanji: "性格", hiragana: "せいかく", example: "彼女は明るい性格だ。" },
  { vietnamese: "Tính chất", kanji: "性質", hiragana: "せいしつ", example: "この薬の性質を調べる。" },
  { vietnamese: "Thứ tự", kanji: "順番", hiragana: "じゅんばん", example: "順番を待つ。" },
  { vietnamese: "Lượt", kanji: "番", hiragana: "ばん", example: "次は私の番だ。" },
  { vietnamese: "Phương pháp", kanji: "方法", hiragana: "ほうほう", example: "新しい方法を試す。" },
  { vietnamese: "Sản phẩm", kanji: "製品", hiragana: "せいひん", example: "この製品は品質が高い。" },
  { vietnamese: "Tăng giá", kanji: "値上がり", hiragana: "ねあがり", example: "ガソリンが値上がりした。" },
  { vietnamese: "Tươi sống", kanji: "生", hiragana: "なま", example: "生の魚を食べる。" }
    ],
    [ // Bài 5
        { vietnamese: "Khát", kanji: "渇く", hiragana: "かわく", example: "水を飲みたい、喉が渇いた。" },
  { vietnamese: "Ngửi", kanji: "嗅ぐ", hiragana: "かぐ", example: "花の香りを嗅ぐ。" },
  { vietnamese: "Đánh, gõ", kanji: "叩く", hiragana: "たたく", example: "ドアを叩いてから入ってください。" },
  { vietnamese: "Đấm", kanji: "殴る", hiragana: "なぐる", example: "怒って壁を殴った。" },
  { vietnamese: "Đá", kanji: "蹴る", hiragana: "ける", example: "ボールを蹴って遊ぶ。" },
  { vietnamese: "Ôm", kanji: "抱く", hiragana: "だく", example: "子供を優しく抱く。" },
  { vietnamese: "Đổ", kanji: "倒れる", hiragana: "たおれる", example: "疲れて倒れそうだ。" },
  { vietnamese: "Làm đổ", kanji: "倒す", hiragana: "たおす", example: "ボウリングのピンを倒す。" },
  { vietnamese: "Thức dậy", kanji: "起きる", hiragana: "おきる", example: "毎朝7時に起きる。" },
  { vietnamese: "Đánh thức", kanji: "起こす", hiragana: "おこす", example: "明日早く起こしてください。" },
  { vietnamese: "Hỏi thăm", kanji: "尋ねる", hiragana: "たずねる", example: "道を尋ねる。" },
  { vietnamese: "Gào", kanji: "叫ぶ", hiragana: "さけぶ", example: "助けてと叫んだ。" },
  { vietnamese: "Giữ yên lặng", kanji: "黙る", hiragana: "だまる", example: "授業中は黙っていてください。" },
  { vietnamese: "Nuôi", kanji: "飼う", hiragana: "かう", example: "犬を飼っている。" },
  { vietnamese: "Đếm", kanji: "数える", hiragana: "かぞえる", example: "お金を数える。" },
  { vietnamese: "Khô", kanji: "乾く", hiragana: "かわく", example: "洗濯物が乾いた。" },
  { vietnamese: "Làm khô", kanji: "乾かす", hiragana: "かわかす", example: "髪を乾かす。" },
  { vietnamese: "Gấp", kanji: "畳む", hiragana: "たたむ", example: "服を畳んで引き出しに入れる。" },
  { vietnamese: "Mời", kanji: "誘う", hiragana: "さそう", example: "友達を食事に誘う。" },
  { vietnamese: "Chiêu đãi", kanji: "奢る", hiragana: "おごる", example: "今日は私が奢るよ。" },
  { vietnamese: "Cất giữ, trông", kanji: "預かる", hiragana: "あずかる", example: "荷物を預かる。" },
  { vietnamese: "Gửi", kanji: "預ける", hiragana: "あずける", example: "銀行にお金を預ける。" },
  { vietnamese: "Được quyết định", kanji: "決まる", hiragana: "きまる", example: "会議の日時が決まった。" },
  { vietnamese: "Quyết định", kanji: "決める", hiragana: "きめる", example: "進路を自分で決める。" },
  { vietnamese: "Được chụp", kanji: "写る", hiragana: "うつる", example: "写真にきれいに写る。" },
  { vietnamese: "Chụp", kanji: "写す", hiragana: "うつす", example: "この景色を写真に写す。" },
  { vietnamese: "Nhớ lại", kanji: "思い出す", hiragana: "おもいだす", example: "昔のことを思い出す。" },
  { vietnamese: "Được dạy", kanji: "教わる", hiragana: "おそわる", example: "先生にピアノを教わる。" },
  { vietnamese: "Đăng ký", kanji: "申し込む", hiragana: "もうしこむ", example: "講座に申し込む。" },
  { vietnamese: "Tắm", kanji: "浴びる", hiragana: "あびる", example: "シャワーを浴びる。" }
    ],
    [ // Bài 6
        { vietnamese: "Từ chối", kanji: "断る", hiragana: "ことわる", example: "無理な頼みを断る。" },
  { vietnamese: "Được tìm thấy", kanji: "見つかる", hiragana: "みつかる", example: "なくした鍵が見つかった。" },
  { vietnamese: "Tìm thấy", kanji: "見つける", hiragana: "みつける", example: "新しいレストランを見つけた。" },
  { vietnamese: "Bị bắt", kanji: "捕まる", hiragana: "つかまる", example: "泥棒が警察に捕まった。" },
  { vietnamese: "Bắt", kanji: "捕まえる", hiragana: "つかまえる", example: "虫を捕まえる。" },
  { vietnamese: "Lên", kanji: "乗る", hiragana: "のる", example: "電車に乗る。" },
  { vietnamese: "Cho lên", kanji: "乗せる", hiragana: "のせる", example: "荷物を車に乗せる。" },
  { vietnamese: "Xuống", kanji: "降りる", hiragana: "おりる", example: "次の駅で降りる。" },
  { vietnamese: "Hạ xuống", kanji: "降ろす", hiragana: "おろす", example: "荷物を降ろす。" },
  { vietnamese: "Khỏi (máy)", kanji: "直る", hiragana: "なおる", example: "パソコンが直った。" },
  { vietnamese: "Sửa", kanji: "直す", hiragana: "なおす", example: "時計を直す。" },
  { vietnamese: "Khỏi bệnh", kanji: "治る", hiragana: "なおる", example: "風邪が治った。" },
  { vietnamese: "Chữa bệnh", kanji: "治す", hiragana: "なおす", example: "医者が病気を治す。" },
  { vietnamese: "Chết", kanji: "亡くなる", hiragana: "なくなる", example: "祖父が亡くなった。" },
  { vietnamese: "Làm mất", kanji: "亡くす", hiragana: "なくす", example: "大切な人を亡くす。" },
  { vietnamese: "Được sinh", kanji: "生まれる", hiragana: "うまれる", example: "赤ちゃんが生まれた。" },
  { vietnamese: "Sinh", kanji: "生む", hiragana: "うむ", example: "母猫が子猫を生んだ。" },
  { vietnamese: "Gặp (tình cờ)", kanji: "出会う", hiragana: "であう", example: "駅で旧友に出会った。" },
  { vietnamese: "Thăm hỏi", kanji: "訪ねる", hiragana: "たずねる", example: "先生の家を訪ねる。" },
  { vietnamese: "Hẹn hò", kanji: "付き合う", hiragana: "つきあう", example: "彼と付き合っている。" },
  { vietnamese: "Hiệu quả", kanji: "効く", hiragana: "きく", example: "この薬はよく効く。" },
  { vietnamese: "Thịnh hành", kanji: "流行る", hiragana: "はやる", example: "この歌が流行っている。" },
  { vietnamese: "Trôi qua", kanji: "経つ", hiragana: "たつ", example: "時間が経つのは早い。" },
  { vietnamese: "Kịp", kanji: "間に合う", hiragana: "まにあう", example: "会議に間に合った。" },
  { vietnamese: "Làm cho kịp", kanji: "間に合わせる", hiragana: "まにあわせる", example: "仕事を締め切りに間に合わせる。" },
  { vietnamese: "Đi lại", kanji: "通う", hiragana: "かよう", example: "学校に毎日通う。" },
  { vietnamese: "Đông", kanji: "込む", hiragana: "こむ", example: "電車が込んでいる。" },
  { vietnamese: "Lướt qua", kanji: "すれ違う", hiragana: "すれちがう", example: "道ですれ違った。" },
  { vietnamese: "Tốn", kanji: "かかる", hiragana: "かかる", example: "時間がかかる作業だ。" },
  { vietnamese: "Treo", kanji: "かける", hiragana: "かける", example: "コートをハンガーにかける。" }
    ],
    [ // Bài 7
        { vietnamese: "Làm chuyển động", kanji: "動かす", hiragana: "うごかす", example: "機械を動かす。" },
  { vietnamese: "Di chuyển", kanji: "動く", hiragana: "うごく", example: "絵が動いているように見える。" },
  { vietnamese: "Tránh xa", kanji: "離れる", hiragana: "はなれる", example: "危ないから離れてください。" },
  { vietnamese: "Rời xa", kanji: "離す", hiragana: "はなす", example: "手を離さないで。" },
  { vietnamese: "Bị va", kanji: "ぶつかる", hiragana: "ぶつかる", example: "自転車が壁にぶつかった。" },
  { vietnamese: "Đâm, va", kanji: "ぶつける", hiragana: "ぶつける", example: "頭をドアにぶつけた。" },
  { vietnamese: "Bị tràn, văng", kanji: "零れる", hiragana: "こぼれる", example: "コップから水が零れた。" },
  { vietnamese: "Làm tràn, văng", kanji: "零す", hiragana: "こぼす", example: "ジュースを零してしまった。" },
  { vietnamese: "Lau, chùi", kanji: "拭く", hiragana: "ふく", example: "テーブルを拭く。" },
  { vietnamese: "Được dọn", kanji: "片付く", hiragana: "かたづく", example: "部屋がきれいに片付いた。" },
  { vietnamese: "Dọn dẹp", kanji: "片付ける", hiragana: "かたづける", example: "机の上を片付ける。" },
  { vietnamese: "Bọc", kanji: "包む", hiragana: "つつむ", example: "プレゼントをきれいに包む。" },
  { vietnamese: "Dán", kanji: "貼る", hiragana: "はる", example: "ポスターを壁に貼る。" },
  { vietnamese: "Làm mất", kanji: "無くす", hiragana: "なくす", example: "鍵を無くしてしまった。" },
  { vietnamese: "Mất, hết", kanji: "無くなる", hiragana: "なくなる", example: "お金が無くなった。" },
  { vietnamese: "Đủ", kanji: "足りる", hiragana: "たりる", example: "お金が足りない。" },
  { vietnamese: "Còn lại", kanji: "残る", hiragana: "のこる", example: "仕事がまだ残っている。" },
  { vietnamese: "Để lại", kanji: "残す", hiragana: "のこす", example: "食べ物を残さないように。" },
  { vietnamese: "Thiu, hỏng", kanji: "腐る", hiragana: "くさる", example: "牛乳が腐っていた。" },
  { vietnamese: "Bong, tróc", kanji: "剥ける", hiragana: "むける", example: "ペンキが剥けてきた。" },
  { vietnamese: "Bóc, gọt", kanji: "剥く", hiragana: "むく", example: "りんごの皮を剥く。" },
  { vietnamese: "Trượt", kanji: "滑る", hiragana: "すべる", example: "氷の上で滑った。" },
  { vietnamese: "Tích tụ", kanji: "積もる", hiragana: "つもる", example: "雪が30cmも積もった。" },
  { vietnamese: "Chất, xếp", kanji: "積む", hiragana: "つむ", example: "荷物をトラックに積む。" },
  { vietnamese: "Trống", kanji: "空く", hiragana: "あく", example: "席が空いている。" },
  { vietnamese: "Làm trống", kanji: "空ける", hiragana: "あける", example: "部屋を空けてください。" },
  { vietnamese: "Giảm", kanji: "下がる", hiragana: "さがる", example: "温度が下がってきた。" },
  { vietnamese: "Làm giảm", kanji: "下げる", hiragana: "さげる", example: "値段を下げる。" },
  { vietnamese: "Lạnh đi", kanji: "冷える", hiragana: "ひえる", example: "ビールがよく冷えている。" },
  { vietnamese: "Làm lạnh", kanji: "冷やす", hiragana: "ひやす", example: "飲み物を冷蔵庫で冷やす。" }
    ],
    [ // Bài 8
        { vietnamese: "Nguội đi", kanji: "冷める", hiragana: "さめる", example: "スープが冷めてしまった。" },
  { vietnamese: "Làm nguội", kanji: "冷ます", hiragana: "さます", example: "お茶を冷まして飲む。" },
  { vietnamese: "Cháy", kanji: "燃える", hiragana: "もえる", example: "家が燃えている！" },
  { vietnamese: "Đốt cháy", kanji: "燃やす", hiragana: "もやす", example: "ゴミを燃やす。" },
  { vietnamese: "Sôi", kanji: "沸く", hiragana: "わく", example: "お湯が沸いた。" },
  { vietnamese: "Đun sôi", kanji: "沸かす", hiragana: "わかす", example: "やかんで水を沸かす。" },
  { vietnamese: "Kêu, reo", kanji: "鳴る", hiragana: "なる", example: "電話が鳴っている。" },
  { vietnamese: "Làm kêu", kanji: "鳴らす", hiragana: "ならす", example: "ベルを鳴らす。" },
  { vietnamese: "Giúp ích", kanji: "役に立つ", hiragana: "やくにたつ", example: "この本は勉強に役に立つ。" },
  { vietnamese: "Làm cho có ích", kanji: "役に立てる", hiragana: "やくにたてる", example: "経験を仕事に役に立てる。" },
  { vietnamese: "Trang trí", kanji: "飾り", hiragana: "かざり", example: "クリスマスツリーの飾りがきれいだ。" },
  { vietnamese: "Chơi", kanji: "遊び", hiragana: "あそび", example: "子供たちが公園で遊んでいる。" },
  { vietnamese: "Tập hợp", kanji: "集まり", hiragana: "あつまり", example: "今日はクラスの集まりがある。" },
  { vietnamese: "Lời dạy", kanji: "教え", hiragana: "おしえ", example: "先生の教えを忘れない。" },
  { vietnamese: "Nhảy", kanji: "踊り", hiragana: "おどり", example: "パーティーで踊りを楽しむ。" },
  { vietnamese: "Ý nghĩ", kanji: "思い", hiragana: "おもい", example: "強い思いを持って頑張る。" },
  { vietnamese: "Suy nghĩ", kanji: "考え", hiragana: "かんがえ", example: "彼の考えは面白い。" },
  { vietnamese: "Việc dọn dẹp", kanji: "片付け", hiragana: "かたづけ", example: "週末に部屋の片付けをする。" },
  { vietnamese: "Sự giúp đỡ", kanji: "手伝い", hiragana: "てつだい", example: "母の手伝いをする。" },
  { vietnamese: "Công việc", kanji: "働き", hiragana: "はたらき", example: "彼の働きは評価されている。" },
  { vietnamese: "Quyết định", kanji: "決まり", hiragana: "きまり", example: "学校の決まりを守る。" },
  { vietnamese: "Ồn ào", kanji: "騒ぎ", hiragana: "さわぎ", example: "外で騒ぎが起きている。" },
  { vietnamese: "Thông báo", kanji: "知らせ", hiragana: "しらせ", example: "重要な知らせが来た。" },
  { vietnamese: "Nhờ", kanji: "頼み", hiragana: "たのみ", example: "友達に頼みごとをする。" },
  { vietnamese: "Mệt", kanji: "疲れ", hiragana: "つかれ", example: "仕事で疲れがたまっている。" },
  { vietnamese: "Sai, khác", kanji: "違い", hiragana: "ちがい", example: "意見の違いがある。" },
  { vietnamese: "Bắt đầu", kanji: "始め", hiragana: "はじめ", example: "会議の始めに挨拶する。" },
  { vietnamese: "Tiếp tục", kanji: "続き", hiragana: "つづき", example: "映画の続きが気になる。" },
  { vietnamese: "Hoàng hôn", kanji: "暮れ", hiragana: "くれ", example: "冬は暮れが早い。" },
  { vietnamese: "Đi, chuyển đi", kanji: "行き", hiragana: "いき", example: "東京行きの電車に乗る。" }
    ],
    [ // Bài 9
        { vietnamese: "Đường về", kanji: "帰り", hiragana: "かえり", example: "帰りの電車は混んでいる。" },
  { vietnamese: "Gấp, vội", kanji: "急ぎ", hiragana: "いそぎ", example: "急ぎの用事ができた。" },
  { vietnamese: "Chậm, muộn", kanji: "遅れ", hiragana: "おくれ", example: "電車が遅れている。" },
  { vietnamese: "Cho vay", kanji: "貸し", hiragana: "かし", example: "お金の貸し借りはしない方がいい。" },
  { vietnamese: "Khoản vay", kanji: "借り", hiragana: "かり", example: "図書館で本を借りる。" },
  { vietnamese: "Thắng", kanji: "勝ち", hiragana: "かち", example: "試合に勝つのは嬉しい。" },
  { vietnamese: "Thua", kanji: "負け", hiragana: "まけ", example: "負けを認める。" },
  { vietnamese: "Đón", kanji: "迎え", hiragana: "むかえ", example: "空港で友達を迎える。" },
  { vietnamese: "Bắt đầu", kanji: "始まり", hiragana: "はじまり", example: "新しい生活の始まりだ。" },
  { vietnamese: "Kết thúc", kanji: "終わり", hiragana: "おわり", example: "映画の終わりが悲しかった。" },
  { vietnamese: "Trở lại", kanji: "戻り", hiragana: "もどり", example: "戻りの切符を買う。" },
  { vietnamese: "Chia ly", kanji: "別れ", hiragana: "わかれ", example: "友達との別れは寂しい。" },
  { vietnamese: "Niềm vui", kanji: "喜び", hiragana: "よろこび", example: "子供の成長が親の喜びだ。" },
  { vietnamese: "Sự thích thú", kanji: "楽しみ", hiragana: "たのしみ", example: "週末の旅行を楽しみにしている。" },
  { vietnamese: "Tiếng cười", kanji: "笑い", hiragana: "わらい", example: "彼の話でみんなが笑いになった。" },
  { vietnamese: "Sự kinh ngạc", kanji: "驚き", hiragana: "おどろき", example: "突然の知らせに驚きを隠せなかった。" },
  { vietnamese: "Sự tức giận", kanji: "怒り", hiragana: "いかり", example: "彼の態度に怒りを感じた。" },
  { vietnamese: "Công việc", kanji: "働き", hiragana: "はたらき", example: "社会での働きが評価された。" },
  { vietnamese: "Kém, không giỏi", kanji: "苦手", hiragana: "にがて", example: "数学は苦手だ。" },
  { vietnamese: "Sự nhàm chán", kanji: "退屈", hiragana: "たいくつ", example: "退屈な会議が続いた。" },
  { vietnamese: "Sức khỏe", kanji: "健康", hiragana: "けんこう", example: "健康に気をつける。" },
  { vietnamese: "Khổ cực", kanji: "苦しい", hiragana: "くるしい", example: "苦しい時期を乗り越えた。" },
  { vietnamese: "Bình tĩnh", kanji: "平気", hiragana: "へいき", example: "彼はどんな時でも平気だ。" },
  { vietnamese: "Ghen tị", kanji: "羨ましい", hiragana: "うらやましい", example: "友達の成功が羨ましい。" },
  { vietnamese: "Ngứa", kanji: "痒い", hiragana: "かゆい", example: "虫に刺されて痒い。" },
  { vietnamese: "Buồn bã", kanji: "悲しい", hiragana: "かなしい", example: "別れが悲しい。" },
  { vietnamese: "Mệt mỏi", kanji: "疲れ", hiragana: "つかれ", example: "仕事の疲れがたまっている。" },
  { vietnamese: "Ngạc nhiên", kanji: "驚く", hiragana: "おどろく", example: "そのニュースに驚いた。" },
  { vietnamese: "Vui vẻ", kanji: "楽しい", hiragana: "たのしい", example: "楽しい時間を過ごした。" },
  { vietnamese: "Cười", kanji: "笑う", hiragana: "わらう", example: "面白い話で笑った。" }
    ],
    [ // Bài 10
        { vietnamese: "Ngoan", kanji: "大人しい", hiragana: "おとなしい", example: "この子はとても大人しい。" },
  { vietnamese: "Chịu đựng tốt", kanji: "我慢強い", hiragana: "がまんづよい", example: "彼は痛みに我慢強い。" },
  { vietnamese: "Chính trực", kanji: "正直", hiragana: "しょうじき", example: "正直に話してください。" },
  { vietnamese: "Keo kiệt", kanji: "けち", hiragana: "けち", example: "彼はけちで有名だ。" },
  { vietnamese: "Bướng bỉnh", kanji: "我儘", hiragana: "わがまま", example: "わがままな子供に困る。" },
  { vietnamese: "Tích cực", kanji: "積極的", hiragana: "せっきょくてき", example: "積極的に発言する。" },
  { vietnamese: "Tiêu cực", kanji: "消極的", hiragana: "しょうきょくてき", example: "消極的な態度を改める。" },
  { vietnamese: "Thỏa mãn", kanji: "満足", hiragana: "まんぞく", example: "結果に満足している。" },
  { vietnamese: "Bất mãn", kanji: "不満", hiragana: "ふまん", example: "不満を上司に伝える。" },
  { vietnamese: "Bất an", kanji: "不安", hiragana: "ふあん", example: "将来に不安を感じる。" },
  { vietnamese: "Vất vả", kanji: "大変", hiragana: "たいへん", example: "大変な仕事を終えた。" },
  { vietnamese: "Không thể", kanji: "無理", hiragana: "むり", example: "一人でやるのは無理だ。" },
  { vietnamese: "Không chú ý", kanji: "不注意", hiragana: "ふちゅうい", example: "不注意なミスをした。" },
  { vietnamese: "Nhàn hạ", kanji: "楽", hiragana: "らく", example: "楽な仕事が欲しい。" },
  { vietnamese: "Phiền phức", kanji: "面倒", hiragana: "めんどう", example: "手続きが面倒だ。" },
  { vietnamese: "Thất lễ", kanji: "失礼", hiragana: "しつれい", example: "失礼なことを言ってしまった。" },
  { vietnamese: "Đương nhiên", kanji: "当然", hiragana: "とうぜん", example: "当然の結果だ。" },
  { vietnamese: "Ngoài dự kiến", kanji: "意外", hiragana: "いがい", example: "意外な展開に驚いた。" },
  { vietnamese: "Khá, đủ", kanji: "結構", hiragana: "けっこう", example: "もう結構です。" },
  { vietnamese: "Sặc sỡ", kanji: "派手", hiragana: "はで", example: "派手な服を着ている。" },
  { vietnamese: "Đơn giản", kanji: "地味", hiragana: "じみ", example: "地味な色を好む。" },
  { vietnamese: "Sang trọng", kanji: "おしゃれ", hiragana: "おしゃれ", example: "おしゃれなカフェに行く。" },
  { vietnamese: "Kỳ lạ", kanji: "変", hiragana: "へん", example: "変な音がする。" },
  { vietnamese: "Kỳ diệu", kanji: "不思議", hiragana: "ふしぎ", example: "不思議な現象が起きた。" },
  { vietnamese: "Tốt hơn", kanji: "まし", hiragana: "まし", example: "ないよりましだ。" },
  { vietnamese: "Lãng phí", kanji: "無駄", hiragana: "むだ", example: "時間を無駄にしたくない。" },
  { vietnamese: "Tự do", kanji: "自由", hiragana: "じゆう", example: "自由な時間が欲しい。" },
  { vietnamese: "Không tự do", kanji: "不自由", hiragana: "ふじゅう", example: "足が不自由な方への配慮が必要だ。" },
  { vietnamese: "Ấm lên", kanji: "温まる", hiragana: "あたたまる", example: "体が温まるスープ。" },
  { vietnamese: "Làm ấm", kanji: "温める", hiragana: "あたためる", example: "ミルクを温める。" }
    ],
    [ // Bài 11
        { vietnamese: "Tăng lên", kanji: "高まる", hiragana: "たかまる", example: "関心が高まっている。" },
  { vietnamese: "Làm tăng", kanji: "高める", hiragana: "たかめる", example: "スキルを高める努力をする。" },
  { vietnamese: "Mạnh lên", kanji: "強まる", hiragana: "つよまる", example: "風が強まってきた。" },
  { vietnamese: "Làm mạnh lên", kanji: "強める", hiragana: "つよめる", example: "チームワークを強める。" },
  { vietnamese: "Yếu đi", kanji: "弱まる", hiragana: "よわまる", example: "痛みが弱まった。" },
  { vietnamese: "Làm yếu đi", kanji: "弱める", hiragana: "よわめる", example: "火の勢いを弱める。" },
  { vietnamese: "Mở rộng", kanji: "広まる", hiragana: "ひろまる", example: "噂が広まっている。" },
  { vietnamese: "Làm lan rộng", kanji: "広める", hiragana: "ひろめる", example: "知識を広める。" },
  { vietnamese: "Sâu sắc", kanji: "深まる", hiragana: "ふかまる", example: "理解が深まった。" },
  { vietnamese: "Làm sâu thêm", kanji: "深める", hiragana: "ふかめる", example: "関係を深める。" },
  { vietnamese: "Chăm sóc", kanji: "世話", hiragana: "せわ", example: "植物の世話をする。" },
  { vietnamese: "Gia đình", kanji: "家庭", hiragana: "かてい", example: "家庭菜園を楽しむ。" },
  { vietnamese: "Hợp tác", kanji: "協力", hiragana: "きょうりょく", example: "プロジェクトに協力する。" },
  { vietnamese: "Cảm ơn", kanji: "感謝", hiragana: "かんしゃ", example: "感謝の気持ちを伝える。" },
  { vietnamese: "Lời cảm ơn", kanji: "お礼", hiragana: "おれい", example: "お礼の手紙を書く。" },
  { vietnamese: "Lời xin lỗi", kanji: "お詫び", hiragana: "おわび", example: "お詫びの言葉を述べる。" },
  { vietnamese: "Cúi chào", kanji: "お辞儀", hiragana: "おじぎ", example: "先生にお辞儀をする。" },
  { vietnamese: "Bắt tay", kanji: "握手", hiragana: "あくしゅ", example: "初対面で握手を交わす。" },
  { vietnamese: "Xấu tính", kanji: "意地悪", hiragana: "いじわる", example: "意地悪をしないで。" },
  { vietnamese: "Nghịch ngợm", kanji: "いたずら", hiragana: "いたずら", example: "子供がいたずらをする。" },
  { vietnamese: "Tiết kiệm", kanji: "節約", hiragana: "せつやく", example: "電気を節約する。" },
  { vietnamese: "Kinh doanh", kanji: "経営", hiragana: "けいえい", example: "会社を経営する。" },
  { vietnamese: "Kiểm điểm", kanji: "反省", hiragana: "はんせい", example: "自分の行動を反省する。" },
  { vietnamese: "Thực hành", kanji: "実行", hiragana: "じっこう", example: "計画を実行に移す。" },
  { vietnamese: "Tiến bộ", kanji: "進歩", hiragana: "しんぽ", example: "日本語が進歩した。" },
  { vietnamese: "Thay đổi", kanji: "変化", hiragana: "へんか", example: "時代の変化に対応する。" },
  { vietnamese: "Phát triển", kanji: "発達", hiragana: "はったつ", example: "技術が発達している。" },
  { vietnamese: "Thể lực", kanji: "体力", hiragana: "たいりょく", example: "体力をつけるために運動する。" },
  { vietnamese: "Tham gia", kanji: "出場", hiragana: "しゅつじょう", example: "大会に出場する。" },
  { vietnamese: "Hoạt động", kanji: "活躍", hiragana: "かつやく", example: "新しい職場で活躍する。" }
    ],
    [ // Bài 12
        { vietnamese: "Cạnh tranh, thi đấu", kanji: "競争", hiragana: "きょうそう", example: "市場での競争が激しい。" },
  { vietnamese: "Cổ vũ", kanji: "応援", hiragana: "おうえん", example: "試合を応援に行く。" },
  { vietnamese: "Vỗ tay", kanji: "拍手", hiragana: "はくしゅ", example: "拍手で迎えられた。" },
  { vietnamese: "Được ưa thích", kanji: "人気", hiragana: "にんき", example: "人気のあるレストラン。" },
  { vietnamese: "Lời đồn", kanji: "噂", hiragana: "うわさ", example: "うわさを信じないで。" },
  { vietnamese: "Thông tin", kanji: "情報", hiragana: "じょうほう", example: "最新情報をチェックする。" },
  { vietnamese: "Trao đổi", kanji: "交換", hiragana: "こうかん", example: "名刺を交換する。" },
  { vietnamese: "Thịnh hành", kanji: "流行", hiragana: "りゅうこう", example: "今流行のファッション。" },
  { vietnamese: "Tuyên truyền", kanji: "宣伝", hiragana: "せんでん", example: "商品を宣伝する。" },
  { vietnamese: "Quảng cáo", kanji: "広告", hiragana: "こうこく", example: "テレビの広告を見る。" },
  { vietnamese: "Chú ý", kanji: "注目", hiragana: "ちゅうもく", example: "注目を集める。" },
  { vietnamese: "Phiên dịch", kanji: "通訳", hiragana: "つうやく", example: "会議で通訳をする。" },
  { vietnamese: "Biên dịch", kanji: "翻訳", hiragana: "ほんやく", example: "小説を翻訳する。" },
  { vietnamese: "Lời nhắn", kanji: "伝言", hiragana: "でんごん", example: "伝言をお願いします。" },
  { vietnamese: "Báo cáo", kanji: "報告", hiragana: "ほうこく", example: "結果を報告する。" },
  { vietnamese: "Ghi hình", kanji: "録画", hiragana: "ろくが", example: "番組を録画する。" },
  { vietnamese: "Đông đúc", kanji: "混雑", hiragana: "こんざつ", example: "電車が混雑している。" },
  { vietnamese: "Thiệt hại", kanji: "被害", hiragana: "ひがい", example: "台風の被害が大きい。" },
  { vietnamese: "Tai nạn", kanji: "事故", hiragana: "じこ", example: "交通事故に遭った。" },
  { vietnamese: "Sửa chữa", kanji: "修理", hiragana: "しゅうり", example: "車を修理する。" },
  { vietnamese: "Mất điện", kanji: "停電", hiragana: "ていでん", example: "停電で真っ暗になった。" },
  { vietnamese: "Động đất", kanji: "地震", hiragana: "じしん", example: "地震に備える。" },
  { vietnamese: "Tự hào", kanji: "自慢", hiragana: "じまん", example: "子供を自慢する。" },
  { vietnamese: "Tắc đường", kanji: "渋滞", hiragana: "じゅうたい", example: "道路が渋滞している。" },
  { vietnamese: "Sự việc", kanji: "事件", hiragana: "じけん", example: "不思議な事件が起きた。" },
  { vietnamese: "Tình trạng", kanji: "調子", hiragana: "ちょうし", example: "体の調子が悪い。" },
  { vietnamese: "Quan tâm", kanji: "関心", hiragana: "かんしん", example: "政治に関心を持つ。" },
  { vietnamese: "Căng thẳng", kanji: "緊張", hiragana: "きんちょう", example: "面接で緊張する。" },
  { vietnamese: "Xung đột", kanji: "衝突", hiragana: "しょうとつ", example: "意見が衝突した。" },
  { vietnamese: "Hỏng", kanji: "故障", hiragana: "こしょう", example: "パソコンが故障した。" }
    ],
    [ // Bài 13
        { vietnamese: "Cảm động", kanji: "感動", hiragana: "かんどう", example: "映画に感動した。" },
  { vietnamese: "Hứng phấn", kanji: "興奮", hiragana: "こうふん", example: "試合を見て興奮する。" },
  { vietnamese: "Cảm tưởng", kanji: "感想", hiragana: "かんそう", example: "読書感想文を書く。" },
  { vietnamese: "Dự đoán", kanji: "予想", hiragana: "よそう", example: "結果を予想する。" },
  { vietnamese: "Chuyên môn", kanji: "専門", hiragana: "せんもん", example: "専門知識が必要だ。" },
  { vietnamese: "Nghiên cứu", kanji: "研究", hiragana: "けんきゅう", example: "新しい技術を研究する。" },
  { vietnamese: "Điều tra", kanji: "調査", hiragana: "ちょうさ", example: "市場調査を行う。" },
  { vietnamese: "Nguyên nhân", kanji: "原因", hiragana: "げんいん", example: "事故の原因を調べる。" },
  { vietnamese: "Kết quả", kanji: "結果", hiragana: "けっか", example: "試験の結果を待つ。" },
  { vietnamese: "Giải quyết", kanji: "解決", hiragana: "かいけつ", example: "問題を解決する。" },
  { vietnamese: "Xác nhận", kanji: "確認", hiragana: "かくにん", example: "予約を確認する。" },
  { vietnamese: "Sử dụng", kanji: "利用", hiragana: "りよう", example: "施設を利用する。" },
  { vietnamese: "Hiểu biết", kanji: "理解", hiragana: "りかい", example: "内容を理解する。" },
  { vietnamese: "Phát hiện", kanji: "発見", hiragana: "はっけん", example: "新しい星を発見した。" },
  { vietnamese: "Phát minh", kanji: "発明", hiragana: "はつめい", example: "重要な発明をする。" },
  { vietnamese: "Bầu cử", kanji: "選挙", hiragana: "せんきょ", example: "選挙に行く。" },
  { vietnamese: "Thuế", kanji: "税金", hiragana: "ぜいきん", example: "税金を払う。" },
  { vietnamese: "Điều kiện", kanji: "条件", hiragana: "じょうけん", example: "条件を満たす。" },
  { vietnamese: "Số lượng", kanji: "数量", hiragana: "すうりょう", example: "数量を確認する。" },
  { vietnamese: "Khu vực", kanji: "辺り", hiragana: "あたり", example: "この辺りに住んでいる。" },
  { vietnamese: "Quan hệ", kanji: "関係", hiragana: "かんけい", example: "両国の関係が深まる。" },
  { vietnamese: "Đoàn thể", kanji: "団体", hiragana: "だんたい", example: "団体で旅行する。" },
  { vietnamese: "Trách nhiệm", kanji: "責任", hiragana: "せきにん", example: "責任を持つ。" },
  { vietnamese: "Tài liệu", kanji: "書類", hiragana: "しょるい", example: "書類を提出する。" },
  { vietnamese: "Hạn chót", kanji: "締め切り", hiragana: "しめきり", example: "締め切りに間に合う。" },
  { vietnamese: "Đường tắt", kanji: "近道", hiragana: "ちかみち", example: "近道を知っている。" },
  { vietnamese: "Trung tâm", kanji: "中心", hiragana: "ちゅうしん", example: "街の中心に行く。" },
  { vietnamese: "Thảo luận", kanji: "討論", hiragana: "とうろん", example: "テーマについて討論する。" },
  { vietnamese: "Phân tích", kanji: "分析", hiragana: "ぶんせき", example: "データを分析する。" },
  { vietnamese: "Đánh giá", kanji: "評価", hiragana: "ひょうか", example: "仕事を評価される。" }
    ],
    [ // Bài 14
        { vietnamese: "Xung quanh", kanji: "周り", hiragana: "まわり", example: "周りを見回す。" },
  { vietnamese: "Lỗ", kanji: "穴", hiragana: "あな", example: "壁に穴を開ける。" },
  { vietnamese: "Phạm vi", kanji: "範囲", hiragana: "はんい", example: "試験範囲を確認する。" },
  { vietnamese: "Thông thường", kanji: "普通", hiragana: "ふつう", example: "普通の生活を送る。" },
  { vietnamese: "Quốc tịch", kanji: "国籍", hiragana: "こくせき", example: "国籍を取得する。" },
  { vietnamese: "Hàng", kanji: "列", hiragana: "れつ", example: "列に並んで待つ。" },
  { vietnamese: "Nội dung", kanji: "内容", hiragana: "ないよう", example: "内容を理解する。" },
  { vietnamese: "Đương nhiên", kanji: "当然", hiragana: "とうぜん", example: "当然の結果だ。" },
  { vietnamese: "Đặc trưng", kanji: "特徴", hiragana: "とくちょう", example: "日本の特徴を学ぶ。" },
  { vietnamese: "Giả", kanji: "偽", hiragana: "にせ", example: "偽のブランド品に注意。" },
  { vietnamese: "Phương Tây", kanji: "西洋", hiragana: "せいよう", example: "西洋の文化に興味がある。" },
  { vietnamese: "Quốc tế", kanji: "国際", hiragana: "こくさい", example: "国際会議に参加する。" },
  { vietnamese: "Tự nhiên", kanji: "自然", hiragana: "しぜん", example: "自然を保護する。" },
  { vietnamese: "Phong cảnh", kanji: "景色", hiragana: "けしき", example: "美しい景色を楽しむ。" },
  { vietnamese: "Tôn giáo", kanji: "宗教", hiragana: "しゅうきょう", example: "宗教の自由を尊重する。" },
  { vietnamese: "Tình yêu", kanji: "愛", hiragana: "あい", example: "家族への愛を感じる。" },
  { vietnamese: "Được gửi đến", kanji: "届く", hiragana: "とどく", example: "荷物が届いた。" },
  { vietnamese: "Gửi đến", kanji: "届ける", hiragana: "とどける", example: "手紙を届ける。" },
  { vietnamese: "Gãi", kanji: "掻く", hiragana: "かく", example: "蚊に刺された所を掻く。" },
  { vietnamese: "Nắm bắt", kanji: "掴む", hiragana: "つかむ", example: "チャンスを掴む。" },
  { vietnamese: "Nắm chặt", kanji: "握る", hiragana: "にぎる", example: "手を握る。" },
  { vietnamese: "Kiềm chế", kanji: "抑える", hiragana: "おさえる", example: "感情を抑える。" },
  { vietnamese: "Tới gần", kanji: "近づく", hiragana: "ちかづく", example: "春が近づいている。" },
  { vietnamese: "Mang tới gần", kanji: "近づける", hiragana: "ちかづける", example: "耳を近づけて聞く。" },
  { vietnamese: "Hợp", kanji: "合う", hiragana: "あう", example: "この服は私に合う。" },
  { vietnamese: "Điều chỉnh", kanji: "合わせる", hiragana: "あわせる", example: "時計を合わせる。" },
  { vietnamese: "Phương Đông", kanji: "東洋", hiragana: "とうよう", example: "東洋の思想を研究する。" },
  { vietnamese: "Văn hóa", kanji: "文化", hiragana: "ぶんか", example: "日本文化を学ぶ。" },
  { vietnamese: "Truyền thống", kanji: "伝統", hiragana: "でんとう", example: "伝統を守る。" },
  { vietnamese: "Phong tục", kanji: "習慣", hiragana: "しゅうかん", example: "地元の習慣に従う。" }
    ],
    [ // Bài 15
        { vietnamese: "Trúng", kanji: "当たる", hiragana: "あたる", example: "くじが当たった。" },
  { vietnamese: "Đánh, chạm", kanji: "当てる", hiragana: "あてる", example: "ボールを壁に当てる。" },
  { vietnamese: "So sánh", kanji: "比べる", hiragana: "くらべる", example: "両者を比べる。" },
  { vietnamese: "Hợp", kanji: "似合う", hiragana: "にあう", example: "この服はあなたに似合う。" },
  { vietnamese: "Giống", kanji: "似る", hiragana: "にる", example: "母親に似ている。" },
  { vietnamese: "Bắt chước", kanji: "似せる", hiragana: "にせる", example: "有名な絵を似せて描く。" },
  { vietnamese: "Được chia", kanji: "分かれる", hiragana: "わかれる", example: "道が二つに分かれる。" },
  { vietnamese: "Phân chia", kanji: "分ける", hiragana: "わける", example: "ケーキを4つに分ける。" },
  { vietnamese: "Cộng thêm", kanji: "足す", hiragana: "たす", example: "数字を足す。" },
  { vietnamese: "Trừ đi", kanji: "引く", hiragana: "ひく", example: "10から3を引く。" },
  { vietnamese: "Tăng lên", kanji: "増える", hiragana: "ふえる", example: "体重が増えた。" },
  { vietnamese: "Làm tăng lên", kanji: "増やす", hiragana: "ふやす", example: "知識を増やす。" },
  { vietnamese: "Giảm đi", kanji: "減る", hiragana: "へる", example: "人口が減っている。" },
  { vietnamese: "Làm giảm đi", kanji: "減らす", hiragana: "へらす", example: "費用を減らす。" },
  { vietnamese: "Thay đổi", kanji: "変わる", hiragana: "かわる", example: "予定が変わった。" },
  { vietnamese: "Làm thay đổi", kanji: "変える", hiragana: "かえる", example: "考え方を変える。" },
  { vietnamese: "Thay thế", kanji: "換わる", hiragana: "かわる", example: "新しい先生に換わる。" },
  { vietnamese: "Đổi", kanji: "換える", hiragana: "かえる", example: "ドルを円に換える。" },
  { vietnamese: "Được trả", kanji: "返る", hiragana: "かえる", example: "お金が返ってきた。" },
  { vietnamese: "Trả lại", kanji: "返す", hiragana: "かえす", example: "借りた本を返す。" },
  { vietnamese: "Nhường", kanji: "譲る", hiragana: "ゆずる", example: "席を譲る。" },
  { vietnamese: "Được giúp", kanji: "助かる", hiragana: "たすかる", example: "あなたのおかげで助かった。" },
  { vietnamese: "Giúp đỡ", kanji: "助ける", hiragana: "たすける", example: "困っている人を助ける。" },
  { vietnamese: "Lừa", kanji: "騙す", hiragana: "だます", example: "人を騙してはいけない。" },
  { vietnamese: "Bắt nạt", kanji: "いじめる", hiragana: "いじめる", example: "弱い者をいじめるな。" },
  { vietnamese: "Trộm", kanji: "盗む", hiragana: "ぬすむ", example: "財布を盗まれた。" },
  { vietnamese: "Bị đâm", kanji: "刺さる", hiragana: "ささる", example: "とげが指に刺さった。" },
  { vietnamese: "Đâm, chích", kanji: "刺す", hiragana: "さす", example: "注射を刺す。" },
  { vietnamese: "Giết", kanji: "殺す", hiragana: "ころす", example: "虫を殺す。" },
  { vietnamese: "Ẩn nấp", kanji: "隠れる", hiragana: "かくれる", example: "木の後ろに隠れる。" }
    ],
    [ // Bài 16
        { vietnamese: "Che giấu", kanji: "隠す", hiragana: "かくす", example: "証拠を隠す。" },
  { vietnamese: "Bị chôn", kanji: "埋まる", hiragana: "うまる", example: "宝物が地面に埋まっている。" },
  { vietnamese: "Chôn", kanji: "埋める", hiragana: "うめる", example: "ごみを埋める。" },
  { vietnamese: "Vây quanh", kanji: "囲む", hiragana: "かこむ", example: "テーブルを囲んで座る。" },
  { vietnamese: "Đầy, tắc", kanji: "詰まる", hiragana: "つまる", example: "鼻が詰まっている。" },
  { vietnamese: "Đóng gói", kanji: "詰める", hiragana: "つめる", example: "荷物を箱に詰める。" },
  { vietnamese: "Mở", kanji: "開く", hiragana: "ひらく", example: "ドアが開く。" },
  { vietnamese: "Bay", kanji: "飛ぶ", hiragana: "とぶ", example: "鳥が空を飛んでいる。" },
  { vietnamese: "Phóng, làm bay", kanji: "飛ばす", hiragana: "とばす", example: "紙飛行機を飛ばす。" },
  { vietnamese: "Rung, lắc", kanji: "振る", hiragana: "ふる", example: "頭を横に振る。" },
  { vietnamese: "Bắt gặp", kanji: "見かける", hiragana: "みかける", example: "街で友人を見かけた。" },
  { vietnamese: "Xác nhận", kanji: "確める", hiragana: "たしかめる", example: "約束を確める。" },
  { vietnamese: "Thử", kanji: "試す", hiragana: "ためす", example: "新しい方法を試す。" },
  { vietnamese: "Lật", kanji: "めくる", hiragana: "めくる", example: "ページをめくる。" },
  { vietnamese: "Lặp lại", kanji: "繰り返す", hiragana: "くりかえす", example: "同じ間違いを繰り返す。" },
  { vietnamese: "Tổ chức", kanji: "行う", hiragana: "おこなう", example: "会議を行う。" },
  { vietnamese: "Sai sót", kanji: "間違う", hiragana: "まちがう", example: "計算を間違う。" },
  { vietnamese: "Nhầm lẫn", kanji: "間違える", hiragana: "まちがえる", example: "道を間違える。" },
  { vietnamese: "Dựng lên", kanji: "立てる", hiragana: "たてる", example: "計画を立てる。" },
  { vietnamese: "Nuôi dưỡng", kanji: "育てる", hiragana: "そだてる", example: "子供を育てる。" },
  { vietnamese: "Dịch", kanji: "訳す", hiragana: "やくす", example: "英語を日本語に訳す。" },
  { vietnamese: "Quen", kanji: "慣れる", hiragana: "なれる", example: "新しい環境に慣れる。" },
  { vietnamese: "Được xây", kanji: "建つ", hiragana: "たつ", example: "新しいビルが建つ。" },
  { vietnamese: "Mọc lên", kanji: "生える", hiragana: "はえる", example: "草が生える。" },
  { vietnamese: "Làm quen", kanji: "慣らす", hiragana: "ならす", example: "体を寒さに慣らす。" },
  { vietnamese: "Xây", kanji: "建てる", hiragana: "たてる", example: "家を建てる。" },
  { vietnamese: "Tha thứ", kanji: "許す", hiragana: "ゆるす", example: "過ちを許す。" },
  { vietnamese: "Được nuôi dưỡng", kanji: "育つ", hiragana: "そだつ", example: "子供が健やかに育つ。" },
  { vietnamese: "Đào", kanji: "掘る", hiragana: "ほる", example: "穴を掘る。" },
  { vietnamese: "Đổ, rót", kanji: "注ぐ", hiragana: "そそぐ", example: "コップに水を注ぐ。" }
    ],
    [ // Bài 17
        { vietnamese: "Trồng trọt, mọc", kanji: "生やす", hiragana: "はやす", example: "ひげを生やす。" },
  { vietnamese: "Bị bẩn", kanji: "汚れる", hiragana: "よごれる", example: "服が汚れた。" },
  { vietnamese: "Làm bẩn", kanji: "汚す", hiragana: "よごす", example: "床を汚さないでください。" },
  { vietnamese: "Bị hỏng", kanji: "壊れる", hiragana: "こわれる", example: "時計が壊れた。" },
  { vietnamese: "Làm hỏng", kanji: "壊す", hiragana: "こわす", example: "おもちゃを壊す。" },
  { vietnamese: "Bị vỡ", kanji: "割れる", hiragana: "われる", example: "コップが割れた。" },
  { vietnamese: "Làm vỡ", kanji: "割る", hiragana: "わる", example: "卵を割る。" },
  { vietnamese: "Gãy", kanji: "折れる", hiragana: "おれる", example: "枝が折れた。" },
  { vietnamese: "Bẻ, gập", kanji: "折る", hiragana: "おる", example: "紙を折る。" },
  { vietnamese: "Bị rách", kanji: "破れる", hiragana: "やぶれる", example: "紙が破れた。" },
  { vietnamese: "Xé, làm rách", kanji: "破る", hiragana: "やぶる", example: "約束を破る。" },
  { vietnamese: "Rẽ, quẹo", kanji: "曲がる", hiragana: "まがる", example: "次の角を右に曲がる。" },
  { vietnamese: "Bẻ cong", kanji: "曲げる", hiragana: "まげる", example: "針金を曲げる。" },
  { vietnamese: "Bung, tuột", kanji: "外れる", hiragana: "はずれる", example: "ボタンが外れた。" },
  { vietnamese: "Tháo, tách", kanji: "外す", hiragana: "はずす", example: "眼鏡を外す。" },
  { vietnamese: "Rung lắc", kanji: "揺れる", hiragana: "ゆれる", example: "地震で家が揺れる。" },
  { vietnamese: "Lung lay, lắc", kanji: "揺らす", hiragana: "ゆらす", example: "揺り椅子を揺らす。" },
  { vietnamese: "Chảy", kanji: "流れる", hiragana: "ながれる", example: "川が流れる。" },
  { vietnamese: "Xả, trôi", kanji: "流す", hiragana: "ながす", example: "水を流す。" },
  { vietnamese: "Ướt", kanji: "濡れる", hiragana: "ぬれる", example: "雨で服が濡れた。" },
  { vietnamese: "Làm ướt", kanji: "濡らす", hiragana: "ぬらす", example: "タオルを水で濡らす。" },
  { vietnamese: "Lạc, do dự", kanji: "迷う", hiragana: "まよう", example: "道に迷う。" },
  { vietnamese: "Lo âu", kanji: "悩む", hiragana: "なやむ", example: "仕事で悩んでいる。" },
  { vietnamese: "Vội vàng", kanji: "慌てる", hiragana: "あわてる", example: "慌てて家を出た。" },
  { vietnamese: "Tỉnh, thức", kanji: "覚める", hiragana: "さめる", example: "夢から覚める。" },
  { vietnamese: "Đánh thức", kanji: "覚ます", hiragana: "さます", example: "目を覚ます。" },
  { vietnamese: "Ngủ", kanji: "眠る", hiragana: "ねむる", example: "ぐっすり眠る。" },
  { vietnamese: "Cầu nguyện", kanji: "祈る", hiragana: "いのる", example: "家族の安全を祈る。" },
  { vietnamese: "Chúc mừng", kanji: "祝う", hiragana: "いわう", example: "誕生日を祝う。" },
  { vietnamese: "Cảm thấy", kanji: "感じる", hiragana: "かんじる", example: "寒さを感じる。" }
    ],
    [ // Bài 18
        { vietnamese: "Bạn cùng lớp", kanji: "", hiragana: "クラスメート", example: "クラスメートと一緒に勉強する。" },
  { vietnamese: "Nhóm", kanji: "", hiragana: "グループ", example: "グループでプロジェクトを行う。" },
  { vietnamese: "Đội", kanji: "", hiragana: "チーム", example: "サッカーチームに入る。" },
  { vietnamese: "Chuyên nghiệp", kanji: "", hiragana: "プロ", example: "プロの選手になる。" },
  { vietnamese: "Nghiệp dư", kanji: "", hiragana: "アマチュア", example: "アマチュア写真家だ。" },
  { vietnamese: "Đào tạo", kanji: "", hiragana: "トレーニング", example: "トレーニングを受ける。" },
  { vietnamese: "Mát xa", kanji: "", hiragana: "マッサージ", example: "肩のマッサージをする。" },
  { vietnamese: "Lời khuyên", kanji: "", hiragana: "アドバイス", example: "先生からアドバイスをもらう。" },
  { vietnamese: "Ý tưởng", kanji: "", hiragana: "アイディア", example: "新しいアイディアを考える。" },
  { vietnamese: "Hàng đầu", kanji: "", hiragana: "トップ", example: "トップレベルを目指す。" },
  { vietnamese: "Tốc độ", kanji: "", hiragana: "スピード", example: "スピードを上げる。" },
  { vietnamese: "Giờ cao điểm", kanji: "", hiragana: "ラッシュ", example: "ラッシュアワーを避ける。" },
  { vietnamese: "Xe máy", kanji: "", hiragana: "バイク", example: "バイクで通勤する。" },
  { vietnamese: "Mũ bảo hiểm", kanji: "", hiragana: "ヘルメット", example: "ヘルメットをかぶる。" },
  { vietnamese: "Kính áp tròng", kanji: "", hiragana: "コンタクトレンズ", example: "コンタクトレンズをつける。" },
  { vietnamese: "Kính", kanji: "", hiragana: "ガラス", example: "ガラスのコップを使う。" },
  { vietnamese: "Nhựa", kanji: "", hiragana: "プラスチック", example: "プラスチックの容器。" },
  { vietnamese: "Ban công", kanji: "", hiragana: "ベランダ", example: "ベランダで洗濯物を干す。" },
  { vietnamese: "Thú cưng", kanji: "", hiragana: "ペット", example: "ペットを飼っている。" },
  { vietnamese: "Ghế dài", kanji: "", hiragana: "ベンチ", example: "公園のベンチに座る。" },
  { vietnamese: "Thiết kế", kanji: "", hiragana: "デザイン", example: "新しいデザインを考える。" },
  { vietnamese: "Đại hạ giá", kanji: "", hiragana: "バーゲンセール", example: "バーゲンセールで買い物する。" },
  { vietnamese: "Làm thêm", kanji: "", hiragana: "パート", example: "パートで働く。" },
  { vietnamese: "Cửa hàng tiện lợi", kanji: "", hiragana: "コンビニ", example: "コンビニでお弁当を買う。" },
  { vietnamese: "Máy tính tiền", kanji: "", hiragana: "レジ", example: "レジで支払う。" },
  { vietnamese: "Hoá đơn", kanji: "", hiragana: "レシート", example: "レシートをもらう。" },
  { vietnamese: "Ăn liền", kanji: "", hiragana: "インスタント", example: "インスタントラーメンを食べる。" },
  { vietnamese: "Đồ ăn nhanh", kanji: "", hiragana: "ファストフード", example: "ファストフード店に行く。" },
  { vietnamese: "Hoa quả", kanji: "", hiragana: "フルーツ", example: "フルーツを買う。" },
  { vietnamese: "Tráng miệng", kanji: "", hiragana: "デザート", example: "デザートにケーキを食べる。" }
    ],
    [ // Bài 19
        { vietnamese: "Mạng", kanji: "", hiragana: "インターネット", example: "インターネットで調べる。" },
  { vietnamese: "Chuông", kanji: "", hiragana: "チャイム", example: "ドアのチャイムが鳴った。" },
  { vietnamese: "Thông báo", kanji: "", hiragana: "アナウンス", example: "空港でアナウンスが流れた。" },
  { vietnamese: "Tin nhắn", kanji: "", hiragana: "メッセージ", example: "メッセージを送る。" },
  { vietnamese: "Tờ rơi", kanji: "", hiragana: "パンフレット", example: "パンフレットをもらう。" },
  { vietnamese: "Dữ liệu", kanji: "", hiragana: "データ", example: "データを分析する。" },
  { vietnamese: "Phần trăm", kanji: "", hiragana: "パーセント", example: "50パーセント割引。" },
  { vietnamese: "Phỏng vấn", kanji: "", hiragana: "インタビュー", example: "テレビでインタビューを受ける。" },
  { vietnamese: "Phiếu điều tra", kanji: "", hiragana: "アンケート", example: "アンケートに答える。" },
  { vietnamese: "Nồng, đậm", kanji: "濃い", hiragana: "こい", example: "コーヒーが濃い。" },
  { vietnamese: "Lạ, kỳ quặc", kanji: "可笑しい", hiragana: "おかしい", example: "彼の行動は可笑しい。" },
  { vietnamese: "Đẹp trai", kanji: "格好いい", hiragana: "かっこういい", example: "あの俳優は格好いい。" },
  { vietnamese: "Giỏi, ngon", kanji: "上手い", hiragana: "うまい", example: "日本語が上手い。" },
  { vietnamese: "Thân thiết", kanji: "親しい", hiragana: "したしい", example: "親しい友人と会う。" },
  { vietnamese: "Chi tiết", kanji: "詳しい", hiragana: "くわしい", example: "詳しい説明を聞く。" },
  { vietnamese: "Tỉ mỉ, nhỏ", kanji: "細かい", hiragana: "こまかい", example: "細かい作業が苦手だ。" },
  { vietnamese: "Nông", kanji: "浅い", hiragana: "あさい", example: "浅い川で遊ぶ。" },
  { vietnamese: "Cứng", kanji: "硬い/固い", hiragana: "かたい", example: "パンが固くなった。" },
  { vietnamese: "Nguội", kanji: "ぬるい", hiragana: "ぬるい", example: "お茶がぬるい。" },
  { vietnamese: "Chói", kanji: "眩しい", hiragana: "まぶしい", example: "太陽が眩しい。" },
  { vietnamese: "Oi bức", kanji: "蒸し暑い", hiragana: "むしあつい", example: "夏は蒸し暑い。" },
  { vietnamese: "Sạch sẽ", kanji: "清潔", hiragana: "せいけつ", example: "清潔な部屋。" },
  { vietnamese: "Tươi", kanji: "新鮮", hiragana: "しんせん", example: "新鮮な野菜。" },
  { vietnamese: "Giàu có, phong phú", kanji: "豊か", hiragana: "ゆたか", example: "豊かな生活。" },
  { vietnamese: "Lộng lẫy, tuyệt vời", kanji: "立派", hiragana: "りっぱ", example: "立派な建物。" },
  { vietnamese: "Chính xác", kanji: "正確", hiragana: "せいかく", example: "正確な情報。" },
  { vietnamese: "Thông minh", kanji: "賢い", hiragana: "かしこい", example: "賢い選択をする。" },
  { vietnamese: "Nhanh nhẹn", kanji: "素早い", hiragana: "すばやい", example: "素早い対応が求められる。" },
  { vietnamese: "Kiên nhẫn", kanji: "我慢強い", hiragana: "がまんづよい", example: "我慢強い性格だ。" },
  { vietnamese: "Dễ thương", kanji: "可愛い", hiragana: "かわいい", example: "可愛い子供。" }
    ],
    [ // Bài 20
        { vietnamese: "Chắc chắn", kanji: "確か", hiragana: "たしか", example: "確か明日は試験だ。" },
  { vietnamese: "Quan trọng", kanji: "重要", hiragana: "じゅうよう", example: "重要な書類を提出する。" },
  { vietnamese: "Cần thiết", kanji: "必要", hiragana: "ひつよう", example: "パスポートが必要だ。" },
  { vietnamese: "Lãng phí", kanji: "勿体ない", hiragana: "もったいない", example: "食べ物を残すのは勿体ない。" },
  { vietnamese: "Tuyệt vời", kanji: "凄い", hiragana: "すごい", example: "凄い技術だ。" },
  { vietnamese: "Tồi tệ", kanji: "酷い", hiragana: "ひどい", example: "酷い天気だ。" },
  { vietnamese: "Mãnh liệt", kanji: "激しい", hiragana: "はげしい", example: "激しい雨が降っている。" },
  { vietnamese: "Giống hệt", kanji: "そっくり", hiragana: "そっくり", example: "母親にそっくりだ。" },
  { vietnamese: "Đột ngột", kanji: "急", hiragana: "きゅう", example: "急に雨が降り出した。" },
  { vietnamese: "Phù hợp", kanji: "適当", hiragana: "てきとう", example: "適当な大きさを選ぶ。" },
  { vietnamese: "Đặc biệt", kanji: "特別", hiragana: "とくべつ", example: "特別な日。" },
  { vietnamese: "Hoàn toàn", kanji: "完全", hiragana: "かんぜん", example: "完全に理解した。" },
  { vietnamese: "Thịnh vượng", kanji: "盛ん", hiragana: "さかん", example: "盛んに議論する。" },
  { vietnamese: "Đa dạng", kanji: "様々", hiragana: "さまざま", example: "様々な意見がある。" },
  { vietnamese: "Khả thi", kanji: "可能", hiragana: "かのう", example: "実施可能な計画だ。" },
  { vietnamese: "Không thể", kanji: "不可能", hiragana: "ふかのう", example: "不可能な要求だ。" },
  { vietnamese: "Cơ bản", kanji: "基本的", hiragana: "きほんてき", example: "基本的なルールを学ぶ。" },
  { vietnamese: "Quốc tế", kanji: "国際的", hiragana: "こくさいてき", example: "国際的な問題だ。" },
  { vietnamese: "Lộn xộn", kanji: "ばらばら", hiragana: "ばらばら", example: "紙がばらばらになった。" },
  { vietnamese: "Rách tả tơi", kanji: "ぼろぼろ", hiragana: "ぼろぼろ", example: "服がぼろぼろだ。" },
  { vietnamese: "Cực kỳ", kanji: "非常に", hiragana: "ひじょうに", example: "非常に重要な会議だ。" },
  { vietnamese: "Rất", kanji: "大変", hiragana: "たいへん", example: "大変疲れた。" },
  { vietnamese: "Hầu hết", kanji: "ほとんど", hiragana: "ほとんど", example: "仕事はほとんど終わった。" },
  { vietnamese: "Đại khái", kanji: "大体", hiragana: "だいたい", example: "大体理解できた。" },
  { vietnamese: "Khá", kanji: "かなり", hiragana: "かなり", example: "かなり遠い場所だ。" },
  { vietnamese: "Tương đối", kanji: "随分", hiragana: "ずいぶん", example: "随分寒くなった。" },
  { vietnamese: "Khá", kanji: "結構", hiragana: "けっこう", example: "結構面白い映画だ。" },
  { vietnamese: "Khá nhiều", kanji: "大分", hiragana: "だいぶ", example: "大分良くなった。" },
  { vietnamese: "Hơn nữa", kanji: "もっと", hiragana: "もっと", example: "もっと頑張ろう。" },
  { vietnamese: "Hoàn toàn", kanji: "すっかり", hiragana: "すっかり", example: "すっかり忘れていた。" }
    ],
    [ // Bài 21
        { vietnamese: "No, đầy", kanji: "一杯", hiragana: "いっぱい", example: "お腹がいっぱいだ。" },
  { vietnamese: "Sát nút", kanji: "ぎりぎり", hiragana: "ぎりぎり", example: "ぎりぎり間に合った。" },
  { vietnamese: "Vừa vặn", kanji: "ぴったり", hiragana: "ぴったり", example: "服がぴったり合う。" },
  { vietnamese: "Thông thường", kanji: "大抵", hiragana: "たいてい", example: "大抵7時に起きる。" },
  { vietnamese: "Trước", kanji: "前", hiragana: "まえ", example: "3日前に会った。" },
  { vietnamese: "Cùng lúc", kanji: "同時に", hiragana: "どうじに", example: "同時に始める。" },
  { vietnamese: "Ngay", kanji: "直ぐに", hiragana: "すぐに", example: "すぐに返事する。" },
  { vietnamese: "Sắp", kanji: "もうすぐ", hiragana: "もうすぐ", example: "もうすぐ夏休みだ。" },
  { vietnamese: "Một chút", kanji: "暫く", hiragana: "しばらく", example: "しばらく待ってください。" },
  { vietnamese: "Đột nhiên", kanji: "突然", hiragana: "とつぜん", example: "突然雨が降り出した。" },
  { vietnamese: "Loáng cái", kanji: "あっという間に", hiragana: "あっというまに", example: "あっという間に終わった。" },
  { vietnamese: "Từ lúc nào không biết", kanji: "いつの間にか", hiragana: "いつのまにか", example: "いつの間にか夜になっていた。" },
  { vietnamese: "Suốt", kanji: "ずっと", hiragana: "ずっと", example: "ずっと待っていた。" },
  { vietnamese: "Như mọi khi", kanji: "相変わらず", hiragana: "あいかわらず", example: "相変わらず元気だ。" },
  { vietnamese: "Lần lượt", kanji: "次々に", hiragana: "つぎつぎに", example: "客が次々に来る。" },
  { vietnamese: "Dần dần", kanji: "どんどん", hiragana: "どんどん", example: "どんどん上手くなる。" },
  { vietnamese: "Càng ngày càng", kanji: "益々", hiragana: "ますます", example: "ますます忙しくなる。" },
  { vietnamese: "Cuối cùng thì", kanji: "やっと", hiragana: "やっと", example: "やっと終わった。" },
  { vietnamese: "Sau cùng thì", kanji: "とうとう", hiragana: "とうとう", example: "とうとう完成した。" },
  { vietnamese: "Cuối cùng thì", kanji: "遂に", hiragana: "ついに", example: "ついに夢が叶った。" },
  { vietnamese: "Tất nhiên", kanji: "勿論", hiragana: "もちろん", example: "もちろん参加する。" },
  { vietnamese: "Quả nhiên", kanji: "矢張り", hiragana: "やはり", example: "やはりそうだった。" },
  { vietnamese: "Chắc chắn", kanji: "きっと", hiragana: "きっと", example: "きっと成功する。" },
  { vietnamese: "Nhất định", kanji: "是非", hiragana: "ぜひ", example: "是非来てください。" },
  { vietnamese: "Cố gắng", kanji: "成るべく", hiragana: "なるべく", example: "なるべく早く来てください。" },
  { vietnamese: "Không ngờ", kanji: "案外", hiragana: "あんがい", example: "案外簡単だった。" },
  { vietnamese: "Có lẽ", kanji: "若しかすると", hiragana: "もしかすると", example: "もしかすると遅れる。" },
  { vietnamese: "Không ngờ", kanji: "まさか", hiragana: "まさか", example: "まさか彼が来るとは。" },
  { vietnamese: "Lơ đễnh", kanji: "うっかり", hiragana: "うっかり", example: "うっかり忘れた。" },
  { vietnamese: "Lỡ", kanji: "つい", hiragana: "つい", example: "つい笑ってしまった。" }
    ],
    [ // Bài 22
        { vietnamese: "Bất giác", kanji: "思わず", hiragana: "おもわず", example: "思わず笑ってしまった。" },
  { vietnamese: "Thở phào", kanji: "ほっと", hiragana: "ほっと", example: "試験が終わってほっとした。" },
  { vietnamese: "Nóng lòng", kanji: "いらいら", hiragana: "いらいら", example: "待ち時間がいらいらする。" },
  { vietnamese: "Thong thả", kanji: "のんびり", hiragana: "のんびり", example: "のんびり休日を過ごす。" },
  { vietnamese: "Thực ra thì", kanji: "実は", hiragana: "じつは", example: "実は私がやったんです。" },
  { vietnamese: "Biểu diễn", kanji: "演奏", hiragana: "えんそう", example: "ピアノの演奏を聴く。" },
  { vietnamese: "Nghệ thuật", kanji: "芸術", hiragana: "げいじゅつ", example: "芸術に興味がある。" },
  { vietnamese: "Kiểm tra", kanji: "検査", hiragana: "けんさ", example: "健康診断で検査を受ける。" },
  { vietnamese: "Máu", kanji: "血液", hiragana: "けつえき", example: "血液型はA型だ。" },
  { vietnamese: "Trị liệu", kanji: "治療", hiragana: "ちりょう", example: "歯の治療をする。" },
  { vietnamese: "Triệu chứng", kanji: "症状", hiragana: "しょうじょう", example: "風邪の症状が出る。" },
  { vietnamese: "Phòng ngừa", kanji: "予防", hiragana: "よぼう", example: "病気の予防接種を受ける。" },
  { vietnamese: "Dinh dưỡng", kanji: "栄養", hiragana: "えいよう", example: "栄養バランスの良い食事。" },
  { vietnamese: "Phẫu thuật", kanji: "手術", hiragana: "しゅじゅつ", example: "来週手術を受ける。" },
  { vietnamese: "Tử vong", kanji: "死亡", hiragana: "しぼう", example: "事故で死亡した。" },
  { vietnamese: "Sinh mệnh", kanji: "命", hiragana: "いのち", example: "命は大切だ。" },
  { vietnamese: "Cuộc sống", kanji: "一生", hiragana: "いっしょう", example: "一生忘れない。" },
  { vietnamese: "Hiểu nhầm", kanji: "誤解", hiragana: "ごかい", example: "誤解を解く。" },
  { vietnamese: "Hối hận", kanji: "後悔", hiragana: "こうかい", example: "後悔しない選択をする。" },
  { vietnamese: "Lý do", kanji: "理由", hiragana: "りゆう", example: "遅れた理由を説明する。" },
  { vietnamese: "Thái độ", kanji: "態度", hiragana: "たいど", example: "態度が悪い。" },
  { vietnamese: "Tật, thói quen", kanji: "癖", hiragana: "くせ", example: "指を噛む癖がある。" },
  { vietnamese: "Lễ nghĩa", kanji: "礼儀", hiragana: "れいぎ", example: "礼儀正しい人。" },
  { vietnamese: "Than phiền", kanji: "文句", hiragana: "もんく", example: "文句を言う。" },
  { vietnamese: "Biểu cảm", kanji: "表情", hiragana: "ひょうじょう", example: "表情が豊かだ。" },
  { vietnamese: "Bề mặt", kanji: "表面", hiragana: "ひょうめん", example: "表面をきれいにする。" },
  { vietnamese: "Cấm", kanji: "禁止", hiragana: "きんし", example: "駐車禁止の場所。" },
  { vietnamese: "Hoàn thành", kanji: "完成", hiragana: "かんせい", example: "作品が完成した。" },
  { vietnamese: "Khôi phục", kanji: "回復", hiragana: "かいふく", example: "健康が回復する。" },
  { vietnamese: "Nguy hiểm", kanji: "危険", hiragana: "きけん", example: "危険な作業だ。" }
    ],
    [ // Bài 23
        { vietnamese: "Vấn đề, chủ đề", kanji: "課題", hiragana: "かだい", example: "今週の課題を提出する。" },
  { vietnamese: "Ngoại lệ", kanji: "例外", hiragana: "れいがい", example: "この規則には例外がない。" },
  { vietnamese: "Cơ bản", kanji: "基本", hiragana: "きほん", example: "基本から勉強し直す。" },
  { vietnamese: "Ghi chép, kỷ lục", kanji: "記録", hiragana: "きろく", example: "世界記録を更新する。" },
  { vietnamese: "Trạng thái", kanji: "状態", hiragana: "じょうたい", example: "健康状態が良い。" },
  { vietnamese: "Sự kiện", kanji: "出来事", hiragana: "できごと", example: "昨日の出来事を話す。" },
  { vietnamese: "Tình huống", kanji: "場面", hiragana: "ばめん", example: "危ない場面に遭遇した。" },
  { vietnamese: "Cơ hội", kanji: "機会", hiragana: "きかい", example: "機会があれば行きたい。" },
  { vietnamese: "Khoảng cách", kanji: "距離", hiragana: "きょり", example: "距離を測る。" },
  { vietnamese: "Thực lực", kanji: "実力", hiragana: "じつりょく", example: "実力を発揮する。" },
  { vietnamese: "Đề xuất", kanji: "提案", hiragana: "ていあん", example: "新しい計画を提案する。" },
  { vietnamese: "Phương tiện", kanji: "手段", hiragana: "しゅだん", example: "交通手段を確保する。" },
  { vietnamese: "Trao đổi", kanji: "やり取り", hiragana: "やりとり", example: "メールでやり取りする。" },
  { vietnamese: "Kiến thức", kanji: "知識", hiragana: "ちしき", example: "専門知識が必要だ。" },
  { vietnamese: "Đại diện", kanji: "代表", hiragana: "だいひょう", example: "クラスの代表になる。" },
  { vietnamese: "Ảnh hưởng", kanji: "影響", hiragana: "えいきょう", example: "環境に影響を与える。" },
  { vietnamese: "Hiệu quả", kanji: "効果", hiragana: "こうか", example: "薬の効果がある。" },
  { vietnamese: "Ấn tượng", kanji: "印象", hiragana: "いんしょう", example: "第一印象が重要だ。" },
  { vietnamese: "Dấu hiệu", kanji: "印", hiragana: "しるし", example: "チェックの印をつける。" },
  { vietnamese: "Tín hiệu", kanji: "合図", hiragana: "あいず", example: "合図で行動を始める。" },
  { vietnamese: "Điểm chung", kanji: "共通", hiragana: "きょうつう", example: "共通の趣味がある。" },
  { vietnamese: "Nhấn mạnh", kanji: "強調", hiragana: "きょうちょう", example: "重要性を強調する。" },
  { vietnamese: "Giản lược", kanji: "省略", hiragana: "しょうりゃく", example: "説明を省略する。" },
  { vietnamese: "Thử thách", kanji: "挑戦", hiragana: "ちょうせん", example: "新しい仕事に挑戦する。" },
  { vietnamese: "Động lực", kanji: "やる気", hiragana: "やるき", example: "やる気が出ない。" },
  { vietnamese: "Dũng cảm", kanji: "勇気", hiragana: "ゆうき", example: "勇気を出して告白する。" },
  { vietnamese: "Tư cách", kanji: "資格", hiragana: "しかく", example: "教師の資格を取る。" },
  { vietnamese: "Đăng ký", kanji: "申請", hiragana: "しんせい", example: "パスポートを申請する。" },
  { vietnamese: "Bản thân", kanji: "本人", hiragana: "ほんにん", example: "本人確認が必要だ。" },
  { vietnamese: "Hợp đồng", kanji: "契約", hiragana: "けいやく", example: "契約を更新する。" }
    ],
    [ // Bài 24
        { vietnamese: "Sự kiên cường", kanji: "強靭", hiragana: "きょうじん", example: "強靭な精神が必要です。" },
        { vietnamese: "Tính kỷ luật", kanji: "規律", hiragana: "きりつ", example: "規律を守って生活します。" }
    ],
    [ // Bài 25
        { vietnamese: "Sự đồng cảm", kanji: "共感", hiragana: "きょうかん", example: "共感を示すことが大切です。" },
        { vietnamese: "Tính trung thực", kanji: "誠実", hiragana: "せいじつ", example: "誠実な態度で接します。" }
    ],
    [ // Bài 26
        { vietnamese: "Sự nhiệt tình", kanji: "熱意", hiragana: "ねつい", example: "熱意を持って取り組んでください。" },
        { vietnamese: "Tính kiên trì", kanji: "根気", hiragana: "こんき", example: "根気強く努力します。" }
    ],
    [ // Bài 27
        { vietnamese: "Sự lạc quan", kanji: "楽観", hiragana: "らっかん", example: "楽観的な考え方が大事です。" },
        { vietnamese: "Tính tự giác", kanji: "自覚", hiragana: "じかく", example: "責任の自覚が必要です。" }
    ],
    [ // Bài 28
        { vietnamese: "Sự hào hứng", kanji: "熱狂", hiragana: "ねっきょう", example: "熱狂的に応援します。" },
        { vietnamese: "Tính tự lập", kanji: "自立", hiragana: "じりつ", example: "自立した生活を目指します。" }
    ],
    [ // Bài 29
        { vietnamese: "Sự chân thành", kanji: "真心", hiragana: "まごころ", example: "真心を込めて対応します。" },
        { vietnamese: "Tính bền vững", kanji: "持続性", hiragana: "じぞくせい", example: "持続性のある計画を作ります。" }
    ],
    [ // Bài 30
        { vietnamese: "Sự thông minh", kanji: "聡明", hiragana: "そうめい", example: "聡明な判断が求められます。" },
        { vietnamese: "Tính hòa hợp", kanji: "調和", hiragana: "ちょうわ", example: "調和の取れた生活を送ります。" }
    ]
];

let currentLesson = 0;
let currentCard = 0;

function populateLessonSelect() {
    const select = document.getElementById('lesson-select');
    for (let i = 1; i <= lessons.length; i++) {
        const option = document.createElement('option');
        option.value = i - 1;
        option.textContent = `Bài ${i}`;
        select.appendChild(option);
    }
}

function displayCard() {
    const card = lessons[currentLesson][currentCard];
    document.getElementById('front-text').textContent = card.vietnamese;
    document.getElementById('kanji').textContent = card.kanji;
    document.getElementById('hiragana').textContent = card.hiragana;
    document.getElementById('example').textContent = card.example;
    document.getElementById('flashcard').classList.remove('flipped');
    document.getElementById('lesson-select').value = currentLesson;
    document.getElementById('card-counter').textContent = `Từ ${currentCard + 1}/${lessons[currentLesson].length}`;
}

function flipCard() {
    document.getElementById('flashcard').classList.toggle('flipped');
}

function nextCard() {
    currentCard = (currentCard + 1) % lessons[currentLesson].length;
    if (currentCard === 0 && currentLesson < lessons.length - 1) {
        currentLesson++;
    }
    displayCard();
}

function prevCard() {
    currentCard = (currentCard - 1 + lessons[currentLesson].length) % lessons[currentLesson].length;
    if (currentCard === lessons[currentLesson].length - 1 && currentLesson > 0) {
        currentLesson--;
    }
    displayCard();
}

function goToLesson() {
    currentLesson = parseInt(document.getElementById('lesson-select').value);
    currentCard = 0;
    displayCard();
}

// Initialize
populateLessonSelect();
displayCard();
